const BOOKING_CANCELLATION_MINUTES = 30;

export const BOOKING_CONFIG = {
    CANCELLATION_MINUTES: BOOKING_CANCELLATION_MINUTES,
    CANCELLATION_MS: BOOKING_CANCELLATION_MINUTES * 60 * 1000,
} as const;